### PR TITLE
Applications under review require this behaviour.

### PR DESCRIPTION
**Pull request by birkirb**
As per:
  http://developer.apple.com/library/ios/#technotes/tn2259/_index.html
    FAQ#16

### CODE REVIEW

**Comment by birkirb** [comment]
Buildhive console log said:

> Gem::InstallError: cover_me requires Ruby version >= 1.9.2.
> An error occurred while installing cover_me (1.2.0), and Bundler cannot continue.

Maybe they need to upgrade their stack?

Travis is happy.

**Comment by nov** [comment]
Thanks

It seems I also need this change for my current project :)

For Buildhive failure, just ignore it.
Recently, I'm gradually stopping ruby 1.8.x support in my gems.
I've just removed itunes-receipt gem from Buildhive list.

**Comment by birkirb** [comment]
No worries. All 1.9.3 here. 
I'll grab the new gem and give it a spin. Thanks!

**Comment by nov** [comment]
Cool.
Now v0.1.3 has these changes.

**Pull request merged**
